spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskly_db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  security:
    jwt:
      secret-key: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      expiration: 8640000
server:
  port: 8888

logging:
  level:
    root: INFO
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG